<?php

namespace ParamountHOA\ParamountHoaEntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerRepository extends EntityRepository
{
    /**
     * @param $lastName
     * @param $emailAddress
     * @param $unitNumber
     * @param $propertyId
     *
     * @return \Doctrine\ORM\AbstractQuery
     */
    public function findBySearchCriteria($lastName, $emailAddress, $unitNumber, $propertyId)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a , b, c
            FROM ParamountHoaEntityBundle:Owner a
            LEFT JOIN a.user b
            LEFT JOIN a.units c
            WHERE (b.emailAddress =  :emailAddress
            OR c.unitNumber = :unitNumber
            OR b.lastName =  :lastName)
            AND b.property = :property'
        )
            ->setParameter('emailAddress', $emailAddress)
            ->setParameter('unitNumber', $unitNumber)
            ->setParameter('lastName', $lastName)
            ->setParameter('property', $propertyId)
            ->getResult();
    }

    public function findById($propertyId, $ownerId)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a
            FROM ParamountHoaEntityBundle:Owner a
            LEFT JOIN a.user b
            WHERE a.id = :id
            AND b.property = :property'
        )
            ->setParameter('id', $ownerId)
            ->setParameter('property', $propertyId)
            ->getResult()[0];
    }
}

