parameters:
#    floridays_entity.example.class: ParamountHOA\ParamountHoaEntityBundle\Example

services:
#    floridays_entity.example:
#        class: %floridays_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
